# Generated by Django 2.1.7 on 2019-03-27 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('priceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddresses',
            fields=[
                ('full_name', models.CharField(default='Full Name', max_length=50, primary_key=True, serialize=False, verbose_name='Fullname')),
                ('ad_P', models.CharField(max_length=100, verbose_name='Address 1')),
                ('ad_P2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2')),
                ('ad_City', models.CharField(max_length=100, verbose_name='City')),
                ('ad_State', models.CharField(max_length=2, verbose_name='State')),
                ('ad_Zip', models.CharField(max_length=5, verbose_name='Zip code')),
                ('ad_full', models.CharField(default=models.CharField(max_length=100, verbose_name='Address 1'), max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
