# Generated by Django 2.1.7 on 2019-03-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0002_useraddresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddresses',
            name='user',
        ),
    ]
