# Generated by Django 2.1.7 on 2019-03-28 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0006_useraddresses_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquotes',
            name='id',
        ),
        migrations.AddField(
            model_name='userquotes',
            name='order_Num',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='userquotes',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='full_name',
            field=models.CharField(default='Full Name', max_length=50, primary_key=True, serialize=False, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='userquotes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
