# Generated by Django 2.1.7 on 2019-03-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0007_auto_20190328_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddresses',
            name='ad_full',
            field=models.CharField(default=models.CharField(max_length=100, verbose_name='Address 1'), max_length=250),
        ),
        migrations.AlterField(
            model_name='userquotes',
            name='reqDelDate',
            field=models.DateField(verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='userquotes',
            name='reqGallons',
            field=models.CharField(max_length=10, verbose_name='Requested Gallons'),
        ),
    ]
