# Generated by Django 2.1.7 on 2019-03-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0008_auto_20190328_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquotes',
            name='reqDelDate',
            field=models.DateField(default='YYYY-MM-DD', verbose_name='Delivery Date'),
        ),
    ]
