# Generated by Django 2.1.7 on 2019-03-30 19:33

from django.db import migrations, models
import priceapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0009_auto_20190330_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquotes',
            name='delivery_address',
            field=models.CharField(default='delivery Address', max_length=300, verbose_name='Delivery Address'),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='ad_Zip',
            field=models.CharField(max_length=9, validators=[priceapp.models.min_len], verbose_name='Zip code'),
        ),
    ]
