# Generated by Django 2.1.7 on 2019-03-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0010_auto_20190330_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquotes',
            name='delivery_address',
            field=models.CharField(max_length=300, verbose_name='Delivery Address'),
        ),
        migrations.AlterField(
            model_name='userquotes',
            name='order_Num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
