# Generated by Django 2.1.7 on 2019-03-31 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0011_auto_20190330_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquotes',
            old_name='order_Num',
            new_name='order_id',
        ),
    ]
