# Generated by Django 2.1.7 on 2019-04-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0014_competitor_price2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor_price2018',
            fields=[
                ('competitor_name', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('Jan', models.SmallIntegerField()),
                ('Feb', models.SmallIntegerField()),
                ('Mar', models.SmallIntegerField()),
                ('Apr', models.SmallIntegerField()),
                ('May', models.SmallIntegerField()),
                ('Jun', models.SmallIntegerField()),
                ('Jul', models.SmallIntegerField()),
                ('Aug', models.SmallIntegerField()),
                ('Sep', models.SmallIntegerField()),
                ('Oct', models.SmallIntegerField()),
                ('Nov', models.SmallIntegerField()),
                ('Dec', models.SmallIntegerField()),
            ],
        ),
    ]
