# Generated by Django 2.1.7 on 2019-04-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0015_competitor_price2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competitor_price2017',
        ),
        migrations.DeleteModel(
            name='Competitor_price2018',
        ),
    ]
