# Generated by Django 2.1.7 on 2019-04-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0019_auto_20190416_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquotes',
            name='pricePerGal',
            field=models.FloatField(default=0.0, verbose_name='Suggested Price'),
        ),
        migrations.AlterField(
            model_name='userquotes',
            name='totalPrice',
            field=models.FloatField(default=0.0, verbose_name='Suggested Price'),
        ),
    ]
