# Generated by Django 2.1.7 on 2019-04-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0021_auto_20190416_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquotes',
            name='reqGallons',
            field=models.FloatField(verbose_name='Requested Gallons'),
        ),
    ]
