# Generated by Django 2.1.7 on 2019-04-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0022_auto_20190416_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddresses',
            name='ad_P',
            field=models.CharField(max_length=100, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='ad_P2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='ad_full',
            field=models.CharField(default=models.CharField(max_length=100, verbose_name='Address 1'), max_length=250),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='full_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Full Name'),
        ),
    ]
