# Generated by Django 2.2 on 2019-04-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0023_auto_20190416_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquotes',
            name='totalPrice',
            field=models.FloatField(default='0.00', verbose_name='Total Price'),
        ),
    ]
