# Generated by Django 2.1.7 on 2019-04-28 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0024_auto_20190418_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddresses',
            name='ad_City',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-z A-Z]*$', 'Only alpha characters are allowed.')], verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='ad_State',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[a-z A-Z]*$', 'Only alpha characters are allowed.')], verbose_name='State'),
        ),
    ]
